on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          apt-get update && \
          apt-get install -y zip && \
          go get -u golang.org/x/lint/golint

      - run: 'echo "VERSION=$(echo ${{ github.ref }} | cut -d/ -f3)" >> $GITHUB_ENV'

      - run: '(echo $VERSION; echo; git cherry -v ${VERSION}^ | cut -d" " -f3-) > CHANGELOG'

      - run: |
          ./build.sh

      - name: Create Release
        run: |
          set -x
          assets=()
          for asset in ./dist/*.zip; do
            assets+=("-a" "$asset")
          done
          hub release crate "${assets[@]}" -F CHANGELOG "$VERSION"
