on:
  push:
    tags:
    - 'v*'

name: Create release from tag

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          apt-get update && \
          apt-get install -y hub zip && \
          go get -u golang.org/x/lint/golint

      - run: 'echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV'

      - run: '(echo $VERSION; echo; git cherry -v $(git describe --abbrev=0 ${VERSION}^) | cut -d" " -f3-) > CHANGELOG'

      - run: |
          ./build.sh

      - run: |
          set -x
          hub release create "$(for zip in ./dist/*.zip; do echo -n "-a $zip "; done)" -F CHANGELOG "$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
